apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: node-test
  name: node-test
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  ports:
  - nodePort: 31626
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: node-test
  type: LoadBalancer
